#:schema node_modules/wrangler/config-schema.json
name = "mutabaah"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"


[[ d1_databases ]]
binding = "DB"
database_name = "habit-tracker"
database_id = "78767e2f-f8fe-4220-ab9f-8cd3079b583f"
migrations_dir = "db/migrations"

